[package]
name = "lamcalc"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A library for creating, parsing and evaluating lambda calculus"
readme = "README.md"
repository = "https://github.com/sshwy/lamcalc"
keywords = ["lambda_calculus", "De_Bruijn_encoding", "parser"]
categories = ["parser-implementations"]
exclude = ["/pkg", "/web"]

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.6"
pest_derive = "2.5.6"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0.94"
wasm-bindgen = "0.2"

[features]
wasm = []
