name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Setup Node & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19
          # cache: yarn
          # cache-dependency-path: web/yarn.lock
      - working-directory: ./web
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Build WASM
        run: wasm-pack build --all-features

      - name: Build Docs
        working-directory: ./web
        run: |
          rm -rf yarn.lock
          YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn
          yarn docs:build-github-pages

      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: web/docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1